// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace protoc_gen_turbolink.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Google.Protobuf.Reflection;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ClientCPP : ClientCPPBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("//Generated by TurboLink CodeGenerator, do not edit!\r\n#include \"");
            
            #line 8 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s.TurboLinkBasicFileName));
            
            #line default
            #line hidden
            this.Write("Client.h\"\r\n#include \"");
            
            #line 9 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s.TurboLinkBasicFileName));
            
            #line default
            #line hidden
            this.Write("Service.h\"\r\n#include \"");
            
            #line 10 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s.CamelFileName));
            
            #line default
            #line hidden
            this.Write("Context.h\"\r\n#include \"TurboLinkGrpcManager_Private.h\"\r\n#include \"Templates/Shared" +
                    "Pointer.h\"\r\n\r\n");
            
            #line 14 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"

foreach(GrpcService service in s.ServiceArray)
{
foreach (GrpcServiceMethod method in service.MethodArray)
{

            
            #line default
            #line hidden
            this.Write("FGrpcContextHandle U");
            
            #line 20 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("Client::Init");
            
            #line 20 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n{\r\n\tFGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHand" +
                    "le();\r\n\tauto context = UGrpcClient::MakeContext<GrpcContext_");
            
            #line 23 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 23 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write(">(handle);\r\n\tcontext->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClien" +
                    "tContext();\r\n");
            
            #line 25 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
if(method.ClientStreaming) {
            
            #line default
            #line hidden
            this.Write("\tcontext->Init();\r\n");
            
            #line 27 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
}
            
            #line default
            #line hidden
            this.Write("\treturn context->GetHandle();\r\n}\r\n\r\nvoid U");
            
            #line 31 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("Client::");
            
            #line 31 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("(FGrpcContextHandle Handle, const ");
            
            #line 31 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.InputType));
            
            #line default
            #line hidden
            this.Write("& Request, FGrpcMetaData MetaData, float DeadLineSeconds)\r\n{\r\n\tauto context = UGr" +
                    "pcClient::GetContext(Handle);\r\n\tif (context != nullptr)\r\n\t{\r\n\t\tauto context");
            
            #line 36 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write(" = StaticCastSharedPtr<GrpcContext_");
            
            #line 36 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 36 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write(">(*context);\r\n\t\tfor (const auto& metaDataPair : MetaData.MetaData)\r\n\t\t{\r\n\t\t\tconte" +
                    "xt");
            
            #line 39 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write(@"->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			context");
            
            #line 49 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("->RpcContext->set_deadline(deadLine);\r\n\t\t}\r\n\t\tcontext");
            
            #line 51 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("->Call(Request);\r\n\t}\r\n}\r\n\r\n");
            
            #line 55 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
if(method.ClientStreaming && !method.ServerStreaming) {
            
            #line default
            #line hidden
            this.Write("void U");
            
            #line 56 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("Client::Stop");
            
            #line 56 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("(FGrpcContextHandle Handle)\r\n{\r\n\tauto context = UGrpcClient::GetContext(Handle);\r" +
                    "\n\tif (context != nullptr)\r\n\t{\r\n\t\tauto context");
            
            #line 61 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write(" = StaticCastSharedPtr<GrpcContext_");
            
            #line 61 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 61 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write(">(*context);\r\n\t\tcontext");
            
            #line 62 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("->Stop();\r\n\t}\r\n}\r\n\r\n");
            
            #line 66 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
}
            
            #line default
            #line hidden
            
            #line 67 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"

}

            
            #line default
            #line hidden
            this.Write("void U");
            
            #line 70 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("Client::TryCancel(FGrpcContextHandle Handle)\r\n{\r\n\tauto context = UGrpcClient::Get" +
                    "Context(Handle);\r\n\tif (context != nullptr)\r\n\t{\r\n\t\t(*context)->TryCancel();\r\n\t}\r\n" +
                    "}\r\n\r\nvoid U");
            
            #line 79 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("Client::Shutdown()\r\n{\r\n");
            
            #line 81 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"

foreach (GrpcServiceMethod method in service.MethodArray)
{

            
            #line default
            #line hidden
            this.Write("\tOn");
            
            #line 85 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("Response.Clear();\r\n");
            
            #line 86 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"

}

            
            #line default
            #line hidden
            this.Write("\tSuper::Shutdown();\r\n}\r\n\r\n");
            
            #line 92 "C:\dev\protoc-gen-turbolink\Template\ClientCPP.tt"

}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ClientCPPBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
