// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace protoc_gen_turbolink.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Google.Protobuf.Reflection;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class MarshalingCPP : MarshalingCPPBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("//Generated by TurboLink CodeGenerator, do not edit!\r\n#include \"");
            
            #line 8 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s.CamelFileName));
            
            #line default
            #line hidden
            this.Write("Marshaling.h\"\r\n");
            
            #line 9 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

foreach (string dependency in s.DependencyFiles)
{

            
            #line default
            #line hidden
            this.Write("#include \"");
            
            #line 13 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency));
            
            #line default
            #line hidden
            this.Write("Marshaling.h\"\r\n");
            
            #line 14 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 16 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
 
foreach(GrpcMessage message in s.MessageArray)
{
	if(message is GrpcMessage_Oneof) continue;
    GenerateMessageMarshalingDefine(message);
}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 23 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

private void ConvertFieldFromGrpcToTurboLink(GrpcMessageField field, string getField)
{

        
        #line default
        #line hidden
        
        #line 27 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
if(field.FieldDesc.Type==FieldDescriptorProto.Types.Type.String) { 
        
        #line default
        #line hidden
        
        #line 27 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("UTF8_TO_TCHAR(");

        
        #line default
        #line hidden
        
        #line 27 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 27 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".c_str())");

        
        #line default
        #line hidden
        
        #line 27 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

}else if(field.FieldDesc.Type==FieldDescriptorProto.Types.Type.Bytes) {
        
        #line default
        #line hidden
        
        #line 28 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("FBytes((const uint8*)");

        
        #line default
        #line hidden
        
        #line 28 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 28 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".c_str(), ");

        
        #line default
        #line hidden
        
        #line 28 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 28 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".length())");

        
        #line default
        #line hidden
        
        #line 28 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

}else if(field.FieldDesc.Type==FieldDescriptorProto.Types.Type.Enum) { 
        
        #line default
        #line hidden
        
        #line 29 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("StaticCast<");

        
        #line default
        #line hidden
        
        #line 29 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldType));

        
        #line default
        #line hidden
        
        #line 29 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(">(");

        
        #line default
        #line hidden
        
        #line 29 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 29 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(")");

        
        #line default
        #line hidden
        
        #line 29 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}
else {
        
        #line default
        #line hidden
        
        #line 30 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 30 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}
        
        #line default
        #line hidden
        
        #line 31 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

}

        
        #line default
        #line hidden
        
        #line 34 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

private void ConvertFieldFromTurboLinkToGrpc(GrpcMessageField field, string getField)
{

        
        #line default
        #line hidden
        
        #line 38 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
if(field.FieldDesc.Type==FieldDescriptorProto.Types.Type.String) { 
        
        #line default
        #line hidden
        
        #line 38 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("TCHAR_TO_UTF8(*(");

        
        #line default
        #line hidden
        
        #line 38 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 38 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("))");

        
        #line default
        #line hidden
        
        #line 38 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

} else if(field.FieldDesc.Type==FieldDescriptorProto.Types.Type.Bytes) { 
        
        #line default
        #line hidden
        
        #line 39 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("std::string((const char*)(");

        
        #line default
        #line hidden
        
        #line 39 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 39 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".Value.GetData()), (size_t)");

        
        #line default
        #line hidden
        
        #line 39 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 39 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".Value.Num())");

        
        #line default
        #line hidden
        
        #line 39 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

} else if(field.FieldDesc.Type==FieldDescriptorProto.Types.Type.Enum) { 
        
        #line default
        #line hidden
        
        #line 40 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldGrpcType));

        
        #line default
        #line hidden
        
        #line 40 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("(static_cast<uint8>(");

        
        #line default
        #line hidden
        
        #line 40 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 40 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("))");

        
        #line default
        #line hidden
        
        #line 40 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

} else {
        
        #line default
        #line hidden
        
        #line 41 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 41 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}
        
        #line default
        #line hidden
        
        #line 42 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

}

        
        #line default
        #line hidden
        
        #line 45 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

private void GenerateMessageMarshalingDefine(GrpcMessage message)
{

        
        #line default
        #line hidden
        
        #line 49 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("void GRPC_TO_TURBOLINK(const ::");

        
        #line default
        #line hidden
        
        #line 49 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(message.GrpcName));

        
        #line default
        #line hidden
        
        #line 49 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("* in, ");

        
        #line default
        #line hidden
        
        #line 49 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(message.Name));

        
        #line default
        #line hidden
        
        #line 49 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("* out)\r\n{\r\n");

        
        #line default
        #line hidden
        
        #line 51 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

    foreach(GrpcMessageField field in message.Fields)
    {

        
        #line default
        #line hidden
        
        #line 55 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

if(field is GrpcMessageField_Map) {
    GrpcMessageField_Map mapField = (GrpcMessageField_Map)field;

        
        #line default
        #line hidden
        
        #line 59 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    out->");

        
        #line default
        #line hidden
        
        #line 59 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.FieldName));

        
        #line default
        #line hidden
        
        #line 59 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".Empty();\r\n    for (const auto& item : in->");

        
        #line default
        #line hidden
        
        #line 60 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 60 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("()) {\r\n");

        
        #line default
        #line hidden
        
        #line 61 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
if(field.NeedNativeMake) { 
        
        #line default
        #line hidden
        
        #line 62 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        ");

        
        #line default
        #line hidden
        
        #line 62 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.ValueField.FieldType));

        
        #line default
        #line hidden
        
        #line 62 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(" field;\r\n        GRPC_TO_TURBOLINK(&item.second, &field);\r\n        out->");

        
        #line default
        #line hidden
        
        #line 64 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.FieldName));

        
        #line default
        #line hidden
        
        #line 64 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".Add(UTF8_TO_TCHAR(item.first.c_str()), MakeShareable(new ");

        
        #line default
        #line hidden
        
        #line 64 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.ValueField.FieldType));

        
        #line default
        #line hidden
        
        #line 64 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("(field)));\r\n");

        
        #line default
        #line hidden
        
        #line 65 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else { 
        
        #line default
        #line hidden
        
        #line 66 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        auto& value = out->");

        
        #line default
        #line hidden
        
        #line 66 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.FieldName));

        
        #line default
        #line hidden
        
        #line 66 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".Add(");

        
        #line default
        #line hidden
        
        #line 66 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromGrpcToTurboLink(mapField.KeyField, "item.first");
        
        #line default
        #line hidden
        
        #line 66 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 67 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
if(mapField.ValueField.FieldDesc.Type==FieldDescriptorProto.Types.Type.Message) { 
        
        #line default
        #line hidden
        
        #line 68 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        GRPC_TO_TURBOLINK(&item.second, &value);\r\n");

        
        #line default
        #line hidden
        
        #line 69 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else {
        
        #line default
        #line hidden
        
        #line 70 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        value = ");

        
        #line default
        #line hidden
        
        #line 70 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromGrpcToTurboLink(mapField.ValueField, "item.second");
        
        #line default
        #line hidden
        
        #line 70 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 71 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}}
        
        #line default
        #line hidden
        
        #line 72 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    }\r\n");

        
        #line default
        #line hidden
        
        #line 73 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

} else if(field is GrpcMessageField_Repeated) { 
    GrpcMessageField_Repeated repeatedField = (GrpcMessageField_Repeated)field;

        
        #line default
        #line hidden
        
        #line 77 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    out->");

        
        #line default
        #line hidden
        
        #line 77 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(repeatedField.FieldName));

        
        #line default
        #line hidden
        
        #line 77 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".Empty();\r\n    for (int i=0; i<in->");

        
        #line default
        #line hidden
        
        #line 78 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(repeatedField.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 78 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("_size(); ++i) {\r\n");

        
        #line default
        #line hidden
        
        #line 79 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
if(field.NeedNativeMake) { 
        
        #line default
        #line hidden
        
        #line 80 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        ");

        
        #line default
        #line hidden
        
        #line 80 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(repeatedField.ItemField.FieldType));

        
        #line default
        #line hidden
        
        #line 80 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(" field;\r\n        GRPC_TO_TURBOLINK(&(in->");

        
        #line default
        #line hidden
        
        #line 81 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(repeatedField.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 81 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("(i)), &field);\r\n        out->");

        
        #line default
        #line hidden
        
        #line 82 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(repeatedField.FieldName));

        
        #line default
        #line hidden
        
        #line 82 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".Add(MakeShareable(new ");

        
        #line default
        #line hidden
        
        #line 82 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(repeatedField.ItemField.FieldType));

        
        #line default
        #line hidden
        
        #line 82 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("(field)));\r\n");

        
        #line default
        #line hidden
        
        #line 83 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else if(field.FieldDesc.Type==FieldDescriptorProto.Types.Type.Message) { 
        
        #line default
        #line hidden
        
        #line 84 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        GRPC_TO_TURBOLINK(&(in->");

        
        #line default
        #line hidden
        
        #line 84 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(repeatedField.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 84 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("(i)), &(out->");

        
        #line default
        #line hidden
        
        #line 84 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(repeatedField.FieldName));

        
        #line default
        #line hidden
        
        #line 84 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".AddZeroed_GetRef()));\r\n");

        
        #line default
        #line hidden
        
        #line 85 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else { string getField = "in->"+repeatedField.FieldGrpcName+"(i)";  
        
        #line default
        #line hidden
        
        #line 86 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        out->");

        
        #line default
        #line hidden
        
        #line 86 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(repeatedField.FieldName));

        
        #line default
        #line hidden
        
        #line 86 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".Add(");

        
        #line default
        #line hidden
        
        #line 86 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromGrpcToTurboLink(repeatedField.ItemField, getField);
        
        #line default
        #line hidden
        
        #line 86 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 87 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}
        
        #line default
        #line hidden
        
        #line 88 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    }\r\n");

        
        #line default
        #line hidden
        
        #line 89 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

} else if(field is GrpcMessageField_Oneof) {
GrpcMessageField_Oneof oneofField = (GrpcMessageField_Oneof)field;
GrpcMessage_Oneof oneofMessage = oneofField.OneofMessage;

        
        #line default
        #line hidden
        
        #line 94 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    switch(in->");

        
        #line default
        #line hidden
        
        #line 94 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(oneofMessage.GrpcName));

        
        #line default
        #line hidden
        
        #line 94 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("_case())\r\n    {\r\n");

        
        #line default
        #line hidden
        
        #line 96 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

foreach(GrpcMessageField fieldOfOneofMessage in oneofMessage.Fields)
{

        
        #line default
        #line hidden
        
        #line 100 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    case ::");

        
        #line default
        #line hidden
        
        #line 100 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(message.GrpcName));

        
        #line default
        #line hidden
        
        #line 100 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("::k");

        
        #line default
        #line hidden
        
        #line 100 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldName));

        
        #line default
        #line hidden
        
        #line 100 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(":\r\n");

        
        #line default
        #line hidden
        
        #line 101 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
if(fieldOfOneofMessage.NeedNativeMake) { 
        
        #line default
        #line hidden
        
        #line 102 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    {\r\n        ");

        
        #line default
        #line hidden
        
        #line 103 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldType));

        
        #line default
        #line hidden
        
        #line 103 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(" field;\r\n        GRPC_TO_TURBOLINK(&(in->");

        
        #line default
        #line hidden
        
        #line 104 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 104 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("()), &field);\r\n        out->");

        
        #line default
        #line hidden
        
        #line 105 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 105 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 105 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldName));

        
        #line default
        #line hidden
        
        #line 105 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("=MakeShareable(new ");

        
        #line default
        #line hidden
        
        #line 105 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldType));

        
        #line default
        #line hidden
        
        #line 105 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("(field));\r\n        out->");

        
        #line default
        #line hidden
        
        #line 106 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 106 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 106 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 106 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("Case = ");

        
        #line default
        #line hidden
        
        #line 106 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(oneofMessage.OneofEnum.Name));

        
        #line default
        #line hidden
        
        #line 106 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("::");

        
        #line default
        #line hidden
        
        #line 106 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldName));

        
        #line default
        #line hidden
        
        #line 106 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(";\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 108 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}else if(fieldOfOneofMessage.FieldDesc.Type==FieldDescriptorProto.Types.Type.Message) { 
        
        #line default
        #line hidden
        
        #line 109 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        GRPC_TO_TURBOLINK(&(in->");

        
        #line default
        #line hidden
        
        #line 109 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 109 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("()), &(out->");

        
        #line default
        #line hidden
        
        #line 109 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 109 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 109 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldName));

        
        #line default
        #line hidden
        
        #line 109 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("));\r\n        out->");

        
        #line default
        #line hidden
        
        #line 110 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 110 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 110 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 110 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("Case = ");

        
        #line default
        #line hidden
        
        #line 110 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(oneofMessage.OneofEnum.Name));

        
        #line default
        #line hidden
        
        #line 110 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("::");

        
        #line default
        #line hidden
        
        #line 110 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldName));

        
        #line default
        #line hidden
        
        #line 110 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 111 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else { string getField = "in->"+fieldOfOneofMessage.FieldGrpcName+"()"; 
        
        #line default
        #line hidden
        
        #line 112 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        out->");

        
        #line default
        #line hidden
        
        #line 112 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 112 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 112 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldName));

        
        #line default
        #line hidden
        
        #line 112 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("=");

        
        #line default
        #line hidden
        
        #line 112 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromGrpcToTurboLink(fieldOfOneofMessage, getField);
        
        #line default
        #line hidden
        
        #line 112 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(";\r\n        out->");

        
        #line default
        #line hidden
        
        #line 113 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 113 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 113 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 113 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("Case = ");

        
        #line default
        #line hidden
        
        #line 113 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(oneofMessage.OneofEnum.Name));

        
        #line default
        #line hidden
        
        #line 113 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("::");

        
        #line default
        #line hidden
        
        #line 113 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldName));

        
        #line default
        #line hidden
        
        #line 113 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 114 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}
        
        #line default
        #line hidden
        
        #line 115 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        break;\r\n");

        
        #line default
        #line hidden
        
        #line 116 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

}

        
        #line default
        #line hidden
        
        #line 119 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    }\r\n");

        
        #line default
        #line hidden
        
        #line 120 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else {
        
        #line default
        #line hidden
        
        #line 121 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
if(field.NeedNativeMake) { 
        
        #line default
        #line hidden
        
        #line 122 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    {\r\n        ");

        
        #line default
        #line hidden
        
        #line 123 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldType));

        
        #line default
        #line hidden
        
        #line 123 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(" field;\r\n        GRPC_TO_TURBOLINK(&(in->");

        
        #line default
        #line hidden
        
        #line 124 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 124 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("()), &field);\r\n        out->");

        
        #line default
        #line hidden
        
        #line 125 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 125 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(" = MakeShareable(new ");

        
        #line default
        #line hidden
        
        #line 125 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldType));

        
        #line default
        #line hidden
        
        #line 125 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("(field));\r\n    }\r\n");

        
        #line default
        #line hidden
        
        #line 127 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}else if(field.FieldDesc.Type==FieldDescriptorProto.Types.Type.Message) { 
        
        #line default
        #line hidden
        
        #line 128 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    GRPC_TO_TURBOLINK(&(in->");

        
        #line default
        #line hidden
        
        #line 128 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 128 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("()), &(out->");

        
        #line default
        #line hidden
        
        #line 128 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 128 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 129 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else { string getField = "in->"+field.FieldGrpcName+"()"; 
        
        #line default
        #line hidden
        
        #line 130 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    out->");

        
        #line default
        #line hidden
        
        #line 130 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 130 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("=");

        
        #line default
        #line hidden
        
        #line 130 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromGrpcToTurboLink(field, getField);
        
        #line default
        #line hidden
        
        #line 130 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 131 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}
        
        #line default
        #line hidden
        
        #line 132 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

    }
}

        
        #line default
        #line hidden
        
        #line 136 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("}\r\n\r\nvoid TURBOLINK_TO_GRPC(const ");

        
        #line default
        #line hidden
        
        #line 138 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(message.Name));

        
        #line default
        #line hidden
        
        #line 138 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("* in, ::");

        
        #line default
        #line hidden
        
        #line 138 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(message.GrpcName));

        
        #line default
        #line hidden
        
        #line 138 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("* out)\r\n{\r\n");

        
        #line default
        #line hidden
        
        #line 140 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

    foreach(GrpcMessageField field in message.Fields)
    {
        var fieldsetName = "set_"+field.FieldGrpcName;

        
        #line default
        #line hidden
        
        #line 145 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

if(field is GrpcMessageField_Map) {
    GrpcMessageField_Map mapField = (GrpcMessageField_Map)field;

        
        #line default
        #line hidden
        
        #line 149 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    for (const auto& item : in->");

        
        #line default
        #line hidden
        
        #line 149 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.FieldName));

        
        #line default
        #line hidden
        
        #line 149 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(") {\r\n");

        
        #line default
        #line hidden
        
        #line 150 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
if(field.NeedNativeMake) { 
        
        #line default
        #line hidden
        
        #line 151 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        ");

        
        #line default
        #line hidden
        
        #line 151 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.ValueField.FieldGrpcType));

        
        #line default
        #line hidden
        
        #line 151 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(" value;\r\n        TURBOLINK_TO_GRPC(item.Value.Get(), &value);\r\n        (*(out->mutable_");

        
        #line default
        #line hidden
        
        #line 153 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 153 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("()))[");

        
        #line default
        #line hidden
        
        #line 153 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromTurboLinkToGrpc(mapField.KeyField, "item.Key");
        
        #line default
        #line hidden
        
        #line 153 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("] = value;\r\n");

        
        #line default
        #line hidden
        
        #line 154 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else if(mapField.ValueField.FieldDesc.Type==FieldDescriptorProto.Types.Type.Message) { 
        
        #line default
        #line hidden
        
        #line 155 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        ");

        
        #line default
        #line hidden
        
        #line 155 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.ValueField.FieldGrpcType));

        
        #line default
        #line hidden
        
        #line 155 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(" value;\r\n        TURBOLINK_TO_GRPC(&item.Value, &value);\r\n        (*(out->mutable_");

        
        #line default
        #line hidden
        
        #line 157 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 157 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("()))[");

        
        #line default
        #line hidden
        
        #line 157 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromTurboLinkToGrpc(mapField.KeyField, "item.Key");
        
        #line default
        #line hidden
        
        #line 157 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("] = value;\r\n");

        
        #line default
        #line hidden
        
        #line 158 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}else {
        
        #line default
        #line hidden
        
        #line 159 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        (*(out->mutable_");

        
        #line default
        #line hidden
        
        #line 159 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(mapField.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 159 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("()))[");

        
        #line default
        #line hidden
        
        #line 159 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromTurboLinkToGrpc(mapField.KeyField, "item.Key");
        
        #line default
        #line hidden
        
        #line 159 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("] = ");

        
        #line default
        #line hidden
        
        #line 159 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromTurboLinkToGrpc(mapField.ValueField, "item.Value");
        
        #line default
        #line hidden
        
        #line 159 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 160 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}
        
        #line default
        #line hidden
        
        #line 161 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    }\r\n");

        
        #line default
        #line hidden
        
        #line 162 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else if(field is GrpcMessageField_Repeated) { 
        
        #line default
        #line hidden
        
        #line 163 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    for(const auto& value : in->");

        
        #line default
        #line hidden
        
        #line 163 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 163 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(") {\r\n");

        
        #line default
        #line hidden
        
        #line 164 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
if(field.NeedNativeMake) { 
        
        #line default
        #line hidden
        
        #line 165 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        TURBOLINK_TO_GRPC(value.Get(), out->add_");

        
        #line default
        #line hidden
        
        #line 165 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 165 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("());\r\n");

        
        #line default
        #line hidden
        
        #line 166 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else if(field.FieldDesc.Type==FieldDescriptorProto.Types.Type.Message) { 
        
        #line default
        #line hidden
        
        #line 167 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        TURBOLINK_TO_GRPC(&value, out->add_");

        
        #line default
        #line hidden
        
        #line 167 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 167 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("());\r\n");

        
        #line default
        #line hidden
        
        #line 168 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else {
        
        #line default
        #line hidden
        
        #line 169 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        out->add_");

        
        #line default
        #line hidden
        
        #line 169 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 169 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 169 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromTurboLinkToGrpc(field, "value");
        
        #line default
        #line hidden
        
        #line 169 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 170 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}
        
        #line default
        #line hidden
        
        #line 171 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    } \r\n");

        
        #line default
        #line hidden
        
        #line 172 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

} else if(field is GrpcMessageField_Oneof) {
GrpcMessageField_Oneof oneofField = (GrpcMessageField_Oneof)field;
GrpcMessage_Oneof oneofMessage = oneofField.OneofMessage;

        
        #line default
        #line hidden
        
        #line 177 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    switch (in->");

        
        #line default
        #line hidden
        
        #line 177 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 177 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 177 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 177 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("Case)\r\n    {\r\n");

        
        #line default
        #line hidden
        
        #line 179 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

foreach(GrpcMessageField fieldOfOneofMessage in oneofMessage.Fields)
{
    string getField = "in->"+field.FieldName + "." + fieldOfOneofMessage.FieldName;

        
        #line default
        #line hidden
        
        #line 184 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    case ");

        
        #line default
        #line hidden
        
        #line 184 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(oneofMessage.OneofEnum.Name));

        
        #line default
        #line hidden
        
        #line 184 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("::");

        
        #line default
        #line hidden
        
        #line 184 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldName));

        
        #line default
        #line hidden
        
        #line 184 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(":\r\n");

        
        #line default
        #line hidden
        
        #line 185 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
if(fieldOfOneofMessage.NeedNativeMake) { 
        
        #line default
        #line hidden
        
        #line 186 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        TURBOLINK_TO_GRPC(");

        
        #line default
        #line hidden
        
        #line 186 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 186 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".Get(), out->mutable_");

        
        #line default
        #line hidden
        
        #line 186 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 186 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("());\r\n");

        
        #line default
        #line hidden
        
        #line 187 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else if(fieldOfOneofMessage.FieldDesc.Type==FieldDescriptorProto.Types.Type.Message) { 
        
        #line default
        #line hidden
        
        #line 188 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        TURBOLINK_TO_GRPC(&(");

        
        #line default
        #line hidden
        
        #line 188 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(getField));

        
        #line default
        #line hidden
        
        #line 188 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("), out->mutable_");

        
        #line default
        #line hidden
        
        #line 188 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 188 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("());\r\n");

        
        #line default
        #line hidden
        
        #line 189 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else { 
        
        #line default
        #line hidden
        
        #line 190 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        out->set_");

        
        #line default
        #line hidden
        
        #line 190 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldOfOneofMessage.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 190 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 190 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromTurboLinkToGrpc(fieldOfOneofMessage, getField);
        
        #line default
        #line hidden
        
        #line 190 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 191 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}
        
        #line default
        #line hidden
        
        #line 192 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("        break;\r\n");

        
        #line default
        #line hidden
        
        #line 193 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

}

        
        #line default
        #line hidden
        
        #line 196 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    }\r\n");

        
        #line default
        #line hidden
        
        #line 197 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else { 
        
        #line default
        #line hidden
        
        #line 198 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
if(field.NeedNativeMake) { 
        
        #line default
        #line hidden
        
        #line 199 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    TURBOLINK_TO_GRPC(in->");

        
        #line default
        #line hidden
        
        #line 199 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 199 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(".Get(), out->mutable_");

        
        #line default
        #line hidden
        
        #line 199 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 199 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("());\r\n");

        
        #line default
        #line hidden
        
        #line 200 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else if(field.FieldDesc.Type==FieldDescriptorProto.Types.Type.Message) { 
        
        #line default
        #line hidden
        
        #line 201 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    TURBOLINK_TO_GRPC(&(in->");

        
        #line default
        #line hidden
        
        #line 201 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldName));

        
        #line default
        #line hidden
        
        #line 201 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("), out->mutable_");

        
        #line default
        #line hidden
        
        #line 201 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.FieldGrpcName));

        
        #line default
        #line hidden
        
        #line 201 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("());\r\n");

        
        #line default
        #line hidden
        
        #line 202 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
} else { string getField = "in->"+field.FieldName; 
        
        #line default
        #line hidden
        
        #line 203 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("    out->");

        
        #line default
        #line hidden
        
        #line 203 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldsetName));

        
        #line default
        #line hidden
        
        #line 203 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 203 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
ConvertFieldFromTurboLinkToGrpc(field, getField);
        
        #line default
        #line hidden
        
        #line 203 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 204 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
}
        
        #line default
        #line hidden
        
        #line 205 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
 
    }
}

        
        #line default
        #line hidden
        
        #line 209 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"
this.Write("}\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 211 "Z:\wilsimpson\protoc-gen-turbolink\Template\MarshalingCPP.tt"

}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class MarshalingCPPBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
