// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace protoc_gen_turbolink.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Google.Protobuf.Reflection;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class NodeH : NodeHBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("//Generated by TurboLink CodeGenerator, do not edit!\r\n#pragma once\r\n#include \"CoreMinimal.h\"\r\n#include \"Kismet/BlueprintAsyncActionBase.h\"\r\n#include \"TurboLinkGrpcClient.h\"\r\n#include \"");
            
            #line 12 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s.CamelFileName));
            
            #line default
            #line hidden
            this.Write("Message.h\"\r\n");
            
            #line 13 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"

if(s.GetTotalPingPongMethodCounts()>0) {

            
            #line default
            #line hidden
            this.Write("#include \"");
            
            #line 16 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s.CamelFileName));
            
            #line default
            #line hidden
            this.Write("Node.generated.h\"\r\n");
            
            #line 17 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 21 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"

foreach(GrpcService service in s.ServiceArray)
{
	int pingPongMethodCounts=0;
	foreach (GrpcServiceMethod method in service.MethodArray) {
		if(!method.ClientStreaming && !method.ServerStreaming) pingPongMethodCounts++;
	}
	if(pingPongMethodCounts==0) continue;

            
            #line default
            #line hidden
            this.Write("class U");
            
            #line 30 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write(";\r\nclass U");
            
            #line 31 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("Client;\r\n");
            
            #line 32 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"

foreach (GrpcServiceMethod method in service.MethodArray)
{
	if(!method.ClientStreaming) {

            
            #line default
            #line hidden
            this.Write("\r\nUCLASS(ClassGroup = TurboLink)\r\nclass TURBOLINKGRPC_API UCall");
            
            #line 39 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            
            #line 39 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write(" : public UBlueprintAsyncActionBase\r\n{\r\n\tGENERATED_BODY()\r\n\r\npublic:\r\n\tDECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(F");
            
            #line 44 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            
            #line 44 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("Delegate, const FGrpcResult&, GrpcResult, const ");
            
            #line 44 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.OutputType));
            
            #line default
            #line hidden
            this.Write("&, Response);\r\n\r\n\tUFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = \"true\", WorldContext = \"WorldContextObject\", DisplayName = \"Call ");
            
            #line 46 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 46 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("\"), Category = \"TurboLink|");
            
            #line 46 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("\")\r\n\tstatic UCall");
            
            #line 47 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            
            #line 47 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("* ");
            
            #line 47 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("(UObject* WorldContextObject, const ");
            
            #line 47 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.InputType));
            
            #line default
            #line hidden
            this.Write("& Request, TMap<FString, FString>& MetaData);\r\n\r\n\tUPROPERTY(BlueprintAssignable)\r\n\tF");
            
            #line 50 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            
            #line 50 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("Delegate On");
            
            #line 50 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("Response;\r\n\r\n");
            
            #line 52 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
if(method.ServerStreaming) {
            
            #line default
            #line hidden
            this.Write("\tUPROPERTY(BlueprintAssignable)\r\n\tF");
            
            #line 54 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            
            #line 54 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("Delegate OnFinished;\r\n\r\n");
            
            #line 56 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
}
            
            #line default
            #line hidden
            this.Write("\tUPROPERTY(BlueprintAssignable)\r\n\tF");
            
            #line 58 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            
            #line 58 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("Delegate OnFail;\r\n\r\nprivate:\r\n\tvirtual void Activate() override;\r\n\r\n\tUPROPERTY()\r\n\tU");
            
            #line 64 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("* ");
            
            #line 64 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\r\n\tUPROPERTY()\r\n\tTObjectPtr<U");
            
            #line 67 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("Client> ");
            
            #line 67 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Name));
            
            #line default
            #line hidden
            this.Write("Client;\r\n\t\r\n\tFGrpcContextHandle Context;\r\n\t");
            
            #line 70 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.InputType));
            
            #line default
            #line hidden
            this.Write(" Request;\r\n\tEGrpcServiceState ServiceState;\r\n\tTMap<FString, FString> MetaData;\r\n\r\n\tUFUNCTION()\r\n\tvoid OnServiceStateChanged(EGrpcServiceState NewState);\r\n\t\r\n\tUFUNCTION()\r\n\tvoid OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);\r\n\r\n\tUFUNCTION()\r\n\tvoid OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const ");
            
            #line 81 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.OutputType));
            
            #line default
            #line hidden
            this.Write("& Response);\r\n\r\n\tvoid Shutdown();\r\n};\r\n");
            
            #line 85 "Z:\wilsimpson\protoc-gen-turbolink\Template\NodeH.tt"

	}
}
}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class NodeHBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
